### ISSUE TITLE
[Suggestion] Enable option for installing as a service.

### ISSUE THREAD

**Issue by soppelmann** [megabytefisher/Eve.TapToClick#1] opened 2020-06-30 14:18 UTC
The autostart of the program is not working so well for me, I have also tried adding it to my "shell:startup" but after suspend the program will quit and require a manual restart and sometimes not automatically start at all.

Installing as a Windows Service might solve this, also allow for it to launch without a gui?
A -minimized flag would be nice

I currently execute it through an autohotkey script but its not ideal. The follow line works for me added to a script i use to remap the brightness keys.

<code>Run, C:\Program Files\Eve.TapToClick\Eve.TapToClick.exe, , Hide</code>

**Comment by ericksontx** [comment] 2020-08-08 07:32
Yes, it is not loading reliably for me either, across multiple Pixelbook installs. Seems to be inconsistent. I tried creating a task in Task Scheduler, but even with elevated privileges and Run as Admin, it still gives a User Access Control permission popup on login.

Is there a way to make it install as a service or as something more integrated, similar to Touchpad Blocker? (https://touchpad-blocker.com/) It's similarly freeware , works 100% of the time after install, loading itself as a background tray service.

**Comment by megabytefisher** [comment] 2020-08-08 08:53
Yeah, I will work on this soon. I have had constant issues with it too. I was trying to find a way to launch with admin privileges without the UAC prompt, and I read that it would work to create a scheduled task with the 'run as admin' attribute. So, I tried that and it worked, but I didn't test enough to realize it was very inconsistent. I think I remember checking, and the scheduled task somehow loses the 'run as admin' tick, and it just doesn't launch at all without it.

I'll try to take a few hours tomorrow to try moving it into a service and hopefully push an update. It annoys me as much as you :)

**Comment by ericksontx** [comment] 2020-08-09 06:49
> Yeah, I will work on this soon. I have had constant issues with it too. I was trying to find a way to launch with admin privileges without the UAC prompt, and I read that it would work to create a scheduled task with the 'run as admin' attribute. So, I tried that and it worked, but I didn't test enough to realize it was very inconsistent. I think I remember checking, and the scheduled task somehow loses the 'run as admin' tick, and it just doesn't launch at all without it.
> 
> I'll try to take a few hours tomorrow to try moving it into a service and hopefully push an update. It annoys me as much as you :)

Great, thank you!

**Comment by ericksontx** [comment] 2021-02-28 21:38
CHecking back on this one, any progress in getting it to start/run reliably at startup, or moving it into being a service? Thanks!

**Comment by ericksontx** [comment] 2021-05-22 00:39
one more time just in case

**Comment by megabytefisher** [comment] 2022-01-08 02:00
Hi guys,

Randomly over the months I have come back to this issue, and I tried several times to rewrite it as a service- however, the problem is that services aren't allow to interact with the desktop/user session. When run as a service, we don't get the raw input messages we need. I tried a few things to get around this, but nothing ever worked.

Today I was looking around, I think I realized the issue with the method we currently use (starting via a scheduled task). I noticed that the option "Start the task only if the computer is on AC power" was checked for the task it created... So I think that's why I originally thought it worked- I was probably on AC power at the time.

I just released version 1.0.6.0 with changes to fix this, and I'm really hoping it's good to go now.

I'll close this issue for now, but please let me know/reopen if you still have issues.

**Closed by megabytefisher** 2022-01-08 02:00 UTC

**Comment by megabytefisher** [comment] 2022-01-08 02:01
By the way, after updating, you will need to uncheck and recheck "Run at startup" so that it recreates the new task with the correct options.
